#服务信息
server:
  port: 9094

spring:
  application:
    name: jenkins-helper
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #数据源配置
  datasource:
    url: jdbc:mysql://10.130.10.45:3306/sonar?useUnicode=true&characterEncoding=utf8
    username: root
    password: coremap_1024++
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化连接大小
      initial-size: 8
      #最小空闲连接数
      min-idle: 5
      #最大连接数
      max-active: 10
      #查询超时时间
      query-timeout: 6000
      #事务查询超时时间
      transaction-query-timeout: 6000
      #关闭空闲连接超时时间
      remove-abandoned-timeout: 1800
      #自动提交,默认:true
      # 配置 DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
      stat-view-servlet:
        # 默认true 内置监控页面首页/druid/index.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: root
        login-password: 123456
        # IP白名单 多个逗号分隔
        allow:
        # IP黑名单
        deny:

# 配置logback
logging:
  level:
    com.navinfo.jenkinshelper: DEBUG
  config: classpath:logback-spring.xml

# Swagger界面内容配置
swagger:
  title: 集成Jenkins打包及其Sonarqube代码检测 API
  description: Jenkins-Helper API 描述
  version: 1.0.0
  contact:
    name: 张卓文
    email: zhangzhuowen@navinfo.com

# mybatis-plus 配置
mybatis-plus:
  type-aliases-package: com.navino.jenkinshelper.entity

# Jenkins请求Url
jenkins:
  oneMap-url: http://10.130.10.45:7878/view/service_code_check/job/
  park-url: http://10.130.10.45:7878/view/park_check/job/
  sonarqube-url: http://10.130.10.45:9015/api/issues/search?componentKeys=
  build-suffix: /build?delay=0sec
  monitor-suffix: /lastBuild/
  sonarqube-suffix: "&s=FILE_LINE&resolved=false&types=BUG&ps=100&facets=severities%2Ctypes&additionalFields=_all"
  cookie: jenkins-timestamper-offset=-28800000; JSESSIONID.8db49794=node0vsesmgonx94d1wb60r5wan61i722.node0; screenResolution=1920x1080; XSRF-TOKEN=5db9vr7d1ojtaqaa1mhpvpscr5; JWT-SESSION=eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJBWGRxekJ6TDlFVGx6NlFMODdmLSIsInN1YiI6ImFkbWluIiwiaWF0IjoxNjEyNDA0NDk3LCJleHAiOjE2MTI2NjM2OTcsImxhc3RSZWZyZXNoVGltZSI6MTYxMjQwNDQ5NzYxMSwieHNyZlRva2VuIjoiNWRiOXZyN2Qxb2p0YXFhYTFtaHB2cHNjcjUifQ.cUPPZTEsj0sHLUe8FKro7i7Gjo2kwQl8ff8Q7FOccJg
# 邮件发送者
navi-email:
  account: zhangzhuowen@navinfo.com
  username: zhangzhuowen
  password: 6560.com